### ISSUE TITLE
C example not the python example

### ISSUE THREAD

**Issue by Neverforgetme** [WangXuan95/FPGA-Gzip-compressor#1]
Dear Wang:

I am harry who always focus on your project about FPGA. And I wonder if I can use the C/C++ example not python when u run the test program on my laptop?

**Comment by WangXuan95** [comment]
Hi,
First of all, thank you for your support to my open-sourced project.

Sure C/C++ can also be used here, but as an auxiliary demo program (rather than an important design program), I wanted to make the design process faster, so I used Python.

In fact, even if you don't know Python, you can take a look at its general execution logic and reproduce it in C.
The Python program here mainly calls the serial port and FPGA communication. Using C to call the serial port under Linux is also simple.
