### ISSUE TITLE
Is the input data width scalable？

### ISSUE THREAD

**Issue by letmeseeOK** [WangXuan95/FPGA-Gzip-compressor#4]
From the code, the input data width is one byte now, can it be scalable to 8 bytes?

**Comment by WangXuan95** [comment]
Hi,
of course, since the input interface is standard AXI-stream, you can use a AXI-stream width transform IP to convert 8-byte-wide stream to 1-byte-wide stream and then send it to my design.
dont forget to star my repo if it is useful for you.

**Comment by letmeseeOK** [comment]
thanks！But the throughput of  data input in my design is 100Mx64bit, So if the compressor is not scalable from 125M*8 to 125M*64bit, I have to find other solution. Anyway, thanks for sharing your good job.

**Comment by WangXuan95** [comment]
A way to enhance performance is multi-core parallelization. i.e., you can design a preprocessor which buffer the input stream and split it into multiple blocks, distribute different blocks to multiple gzip cores to compress. then, design a post-processor to recover multiple output streams to original order. however, by this way you will get multiple gzip streams instead of one single large gzip stream. so this is just a alternative advice
